In [7]:
# Query google and find the top colleges list
from googlesearch import search
import pandas as pd
import requests
from bs4 import BeautifulSoup
import re

In [18]:
class GoogleQuery:
    def __init__(self, query):
        self.query = query
    
    def fetch_urls(self):
        print("Fetching Results:")
        df = {}
        for idx, result in enumerate(search(self.query, num_results=10), start=1):
            df[idx] = result
        return pd.DataFrame(df.items(), columns=['rank', 'result'])

In [124]:
class bsparse:
    def __init__(self, url):
        self.url = url
    
    def parse_urls(self):
        headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0'}
        response = requests.get(self.url, headers = headers, timeout=5)
        soup = BeautifulSoup(response.content, "html.parser")
        heading = soup.find_all('h3', )
        college_list = []
        for head in heading:
            try:
                val = head.string
                college_list.append(head.string)
            except:
                val = None
                college_list.append("error")            
        return college_list

In [121]:
cities = ["Hyderabad","Bangalore","Kolkata","Delhi","Mumbai","Chennai","Kerala","Karnataka","Telengana","Andhra Pradesh","Shillong","Guwahati","Assam","Meghalaya","Tripura","Sikkim"]
clg_list = []
for city in cities:
    a = GoogleQuery(f"Top Commerce Colleges in {city}")
    df = a.fetch_urls()
    df = df[df['result'].str.contains('iide')]
    clg_list.append(df)
final_df = pd.concat(clg_list)
final_df = final_df.drop_duplicates(subset = ["result"])
final_df

Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:

   rank                                             result
5     6  https://iide.co/blog/commerce-colleges-in-hyde...
2     3  https://iide.co/blog/commerce-colleges-in-bang...
2     3  https://iide.co/blog/commerce-colleges-in-kolk...
2     3  https://iide.co/blog/commerce-colleges-in-mumbai/
0     1  https://iide.co/blog/commerce-colleges-in-guwa...

In [122]:
final_df

   rank                                             result
5     6  https://iide.co/blog/commerce-colleges-in-hyde...
2     3  https://iide.co/blog/commerce-colleges-in-bang...
2     3  https://iide.co/blog/commerce-colleges-in-kolk...
2     3  https://iide.co/blog/commerce-colleges-in-mumbai/
0     1  https://iide.co/blog/commerce-colleges-in-guwa...

In [167]:
final_clg = {}
for link in final_df["result"].to_list():
    b = bsparse(link)
    l = b.parse_urls()
    l = [i for i in l if i]
    pattern = r'[0-9]*[.]'
    l = [i for i in l if re.match(pattern,i[0:3])]
    final_clg[link.split("-")[-1]] = l
final_colleges = pd.DataFrame(dict([ (k,pd.Series(v)) for k,v in final_clg.items() ]))

In [251]:
def get_email_contacts(url):
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0'}
    response = requests.get(url, headers = headers, timeout=5)
    soup = BeautifulSoup(response.content, "html.parser")
    mailtos = soup.select('a[href]')
    all_emails = []
    for i in mailtos:
        if "mailto" in i["href"]:
            all_emails.append((i["href"].replace("mailto:","")))
    return all_emails

In [252]:
final_colleges

,hyderabad/,bangalore/,kolkata/,mumbai/,guwahati/
0,1. St Francis College for Women,1.St. Joseph’s College of Commerce,1. Bhawanipur Education Society College,1. Thakur College of Science & Commerce,1. Pandu College
1,2. St. Ann’s College,3.Presidency College,2. Goenka College of Commerce & Business Admin...,2. Narsee Monjee College of Commerce and Econo...,2. Gauhati Commerce College
2,"3. Telangana Mahila Viswavidyalayam, Hyderabad",4.Christ University,3. JD Birla Institute,3. KES Shroff College (Autonomous),3. Royal Global University
3,5. Indian Institute of Management and Commerce,5. Kristu Jayanti College,4. St.Xavier’s College,4. KPB Hinduja College,4. Dispur College
4,6. Woxsen School of Business,7.Surana College,"5. Amity University, Kolkata","5. Pillai College of Arts, Commerce & Science ...",5. Assam Don Bosco University
5,7. Badruka College of Commerce and Arts,9. ISBR Business School,"6. Sister Nivedita University, Kolkata",6. Mithibai College,6. Paschim Guwahati Mahavidyalaya
6,"8. IBS, Hyderabad",10. St Claret College(SCC),7. Maulana Azad College,7. H.R. College of Commerce and Economics,7. North Eastern Regional Institution of Manag...
7,"9. Nizam College, Hyderabad",12. Vijaya College,8. Shri Shikshayatan College,8. Kishinchand Chellaram College,8. Pragjyotish College
8,10. A.V. College of Arts Science and Commerce,NaN,"9. Sivanth Shastri College, Kolkata",9. Jai Hind College,9. KC Das Commerce College
9,11. Osmania University (Department of Commerce),NaN,10. Acharya Jagadish Chandra Bose College,10. St.Xavier’s College,10. Krishna Kanta Handiqui State Open Universi...
10,12. Government City College,NaN,11. Techno India University,11. Ramniranjan Anandilal Podar College of Com...,11. Jettwings Academy
11,13. Avinash College of Commerce,NaN,12. Scottish Church College,"12. D.G. Ruparel College of Art, Science, and ...",13. Lumding College
12,14. Villa Marie College,NaN,13. Rammohan College,13. KJ Somaiya College of Arts and Commerce,"15. Bengtol College, Guwahati"
13,15. Bhavan’s Vivekananda College,NaN,14. University of Calcutta,14. Sydenham College of Commerce and Economics,16. Gauhati University
14,16. Jagruti Degree and P.G. College,NaN,16. Acharya Girish Chandra Bose College,15. Lala Lajpat Rai College of Commerce and Ec...,17. Icon Commerce College
15,17. Loyola Academy,NaN,17. Surendranath College,"16. SIES College of Arts, Science and Commerce",18. Radha Govinda Baruah College
16,18. Vivekananda Degree College,NaN,18. City College,17. Ramnarain Ruia College,19. Guwahati College
17,19. St. Mary’s College,NaN,19. City College of Commerce and Business Admi...,18. Wilson College,20. NEF College
18,20. Kasturba Gandhi Degree & PG College for Women,NaN,NaN,"19. St Andrews College of Arts, Science and Co...",21. Karmashree Hiteswar Saikia College
19,NaN,NaN,NaN,1. Bachelors in Commerce(B.Com),NaN
20,NaN,NaN,NaN,3. Bachelor of Management Studies (BMS),NaN
21,NaN,NaN,NaN,4. Bachelor of Vocation (B.Voc),NaN
22,NaN,NaN,NaN,5. Bachelor of Mass Media (BMM),NaN
23,NaN,NaN,NaN,6. Bachelor of Accounting and Finance (BAF),NaN
24,NaN,NaN,NaN,7. Bachelor of Financial Markets (BFM),NaN
25,NaN,NaN,NaN,8. LLB (Bachelor of Law),NaN

In [254]:
contact_df = pd.DataFrame(columns = ["city","college","url","emails"])
i=0
import numpy as np
for city in final_colleges.columns:
    clgs = final_colleges[city]
    clg_list = clgs.dropna().to_list()
    clg_list =[re.sub(r'[0-9.]+', '', s) for s in clg_list]
    for clg in clg_list:
        a= GoogleQuery(f"{clg} placement contact")
        import time
        time.sleep(15)
        df = a.fetch_urls()
        try:
            url = df["result"].iloc[0]
            emails = get_email_contacts(url)
        except:
            url = None
            emails = None
        contact_df.loc[i] = [city,clg,url,emails]
        i=i+1
print(contact_df)

Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:

Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.

Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
Fetching Results:
          city                                       college  \
0   hyderabad/                  St Francis College for Women
1   hyderabad/                              St Ann’s College
2   hyderabad/   Telangana Mahila Viswavidyalayam, Hyderabad
3   hyderabad/   Indian Institute of Management and Commerce
4   hyderabad/                     Woxsen School of Business
..         ...                                           ...
85   guwahati/                         Icon Commerce College
86   guwahati/                  Radha Govinda Baruah College
87   guwahati/                              Guwahati College
88   guwahati/                                   NEF College
89   guwahati/            Karmashree Hiteswar Saikia College

                                                  url  \
0   https://www.sfc.ac.in/career-guidance-placemen...
1            https://stannscollegehyd.com/placements/
2    https://www.oucwkoti.ac.in/aboutus-contactus.php
3        https://www.iimb.ac.in/recruiters_contact_us
4                   https://woxsen.edu.in/placements/
..                                                ...
85            https://iconcommercecollege.in/contacts
86                 https://www.rgbaruahcollege.ac.in/
87  https://www.guwahaticollege.org.in/carrercounc...
88           https://www.nefcollege.com/contactus.php
89                                               None

                                               emails
0                                 [#, info@sfc.ac.in]
1   [stann_college@yahoo.co.in, stann_college@yaho...
2                                                  []
3   [nishant.verma@iimb.ac.in, tapasr.pati@iimb.ac...
4                                                  []
..                                                ...
85                                                 []
86                                                 []
87  [ppalguwahaticollege@gmail.com, ppalguwahatico...
88     [nefcollege1@gmail.com, nefcollege1@gmail.com]
89                                               None

[90 rows x 4 columns]

In [259]:
contact_df.to_excel("college_list.xlsx")

In [257]:
pip install openpyxl

Collecting openpyxl
  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.